- name: Update apt and install apt packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  become: yes
  loop:
    - "build-essential"
    - "libssl-dev"
    - "python3-distutils"
    - "bluez" 
    - "bluez-tools"
    - "blueman" # Bluetooth manager blueman-manager
    - "curl"
    - "terminator"
    - "vim"
    - "zsh"
    - "openfortivpn"
    - "htop"
    - "tldr"
    - "awscli"
    - "pavucontrol" # volume control
    - "ffmpeg"
    - "i3"
    # - "docker" # Not sure if this is the correct package name for docker

    #TODO - ohmyzsh
    #TODO - "nvm"
      # TODO - install node
      # TODO - then can be joplin-cli installed
        # npm -g install joplin

    #TODO - "pyenv" https://www.liquidweb.com/kb/how-to-install-pyenv-on-ubuntu-18-04/
    #TODO - "jq" # This is required for project template ansible mirror_prepare.sh
    #TODO - "yq" # This is required for project template ansible mirror_prepare.sh
    
- name: Install snap packages
  snap:
    classic: yes
    name: "{{ item }}"
    state: present
  become: yes
  loop:
    - "pycharm-professional"
    - "discord"
    - "vlc"
    - "gitkraken"
    - "slack"
    - "spotify"
    - "gimp"
    - "bw"
    - "micro"

# Running and install docker is not working correctly on ubuntu. Need to be implemented
# https://docs.docker.com/engine/install/ubuntu/

# One example found from digital ocean - did not manage to get it working properly
# https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-20-04