- name: Check if oh my zsh is installed
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: oh_my_zsh_installed

- name: Install oh my zsh
  shell: >
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not oh_my_zsh_installed.stat.exists or not oh_my_zsh_installed.stat.isdir

- name: Update zshrc
  template:
    src: zshrc
    dest: "~/.zshrc"
    mode: 0644
